source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def testing_pods
   pod 'Quick', '~> 2.1.0'
   pod 'Nimble', '8.0.2'
end

target 'HealthKitSampleGenerator_Example' do
  pod "HealthKitSampleGenerator", :path => "../"
end

target 'HealthKitSampleGenerator_Tests' do
  pod "HealthKitSampleGenerator", :path => "../"
  testing_pods
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
