# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
notifications:
  slack:
    on_success: never
    on_failure: never
    on_start: never

osx_image: xcode7	 
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script: 
#- set -o pipefail && xcodebuild test -workspace Example/HealthKitSampleGenerator.xcworkspace -list
#- set -o pipefail && xcodebuild test -workspace Example/HealthKitSampleGenerator.xcworkspace -scheme TravisCiTest -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO OTHER_SWIFT_FLAGS='-DTRAVIS' | xcpretty -c
- pod lib lint --quick
